/*
 * Gamedev Framework (gf)
 * Copyright (C) 2016-2017 Julien Bernard
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 */

#ifndef GF_ALL_H
#define GF_ALL_H

#include "Action.h"
#include "Activities.h"
#include "Activity.h"
#include "Alignment.h"
#include "Anchor.h"
#include "AnimatedSprite.h"
#include "Animation.h"
#include "Array2D.h"
#include "ArrayRef.h"
#include "AssetManager.h"
#include "Blend.h"
#include "BufferedGeometry.h"
#include "BufferRef.h"
#include "Circ.h"
#include "Clipboard.h"
#include "Clock.h"
#include "Collision.h"
#include "Color.h"
#include "ColorRamp.h"
#include "ConsoleChar.h"
#include "ConsoleFont.h"
#include "Console.h"
#include "Control.h"
#include "Controls.h"
#include "Coordinates.h"
#include "Cursor.h"
#include "Curve.h"
#include "Curves.h"
#include "Direction.h"
#include "Drawable.h"
#include "Easings.h"
#include "Effect.h"
#include "Effects.h"
#include "EntityContainer.h"
#include "Entity.h"
#include "Event.h"
#include "Flags.h"
#include "Font.h"
#include "Gamepad.h"
#include "Geometry.h"
#include "GraphicsInfo.h"
#include "Grid.h"
#include "Heightmap.h"
#include "Id.h"
#include "Image.h"
#include "InputStream.h"
#include "InputStreams.h"
#include "Keyboard.h"
#include "Library.h"
#include "Log.h"
#include "Logo.h"
#include "Map.h"
#include "Math.h"
#include "Matrix.h"
#include "Message.h"
#include "MessageManager.h"
#include "ModelContainer.h"
#include "Model.h"
#include "Models.h"
#include "Monitor.h"
#include "Mouse.h"
#include "NinePatch.h"
#include "Noise.h"
#include "Noises.h"
#include "Orientation.h"
#include "Particles.h"
#include "Path.h"
#include "Paths.h"
#include "PhysicsBody.h"
#include "PhysicsGeometry.h"
#include "PhysicsModel.h"
#include "Polygon.h"
#include "Polyline.h"
#include "Portability.h"
#include "PostProcessing.h"
#include "PrimitiveType.h"
#include "Queue.h"
#include "Random.h"
#include "Range.h"
#include "Rect.h"
#include "Region.h"
#include "RenderPipeline.h"
#include "RenderStates.h"
#include "RenderTarget.h"
#include "RenderTexture.h"
#include "RenderWindow.h"
#include "ResourceManager.h"
#include "Rune.h"
#include "Shader.h"
#include "Shape.h"
#include "Shapes.h"
#include "Singleton.h"
#include "Sleep.h"
#include "SpaceTree.h"
#include "SpriteBatch.h"
#include "Sprite.h"
#include "StringRef.h"
#include "StringUtils.h"
#include "SystemInfo.h"
#include "Text.h"
#include "TextureAtlas.h"
#include "Texture.h"
#include "TileLayer.h"
#include "Time.h"
#include "Tmx.h"
#include "Transformable.h"
#include "Transform.h"
#include "Tween.h"
#include "Types.h"
#include "UI.h"
#include "Unused.h"
#include "Vector.h"
#include "VectorOps.h"
#include "VertexArray.h"
#include "VertexBuffer.h"
#include "Vertex.h"
#include "ViewContainer.h"
#include "View.h"
#include "Views.h"
#include "Window.h"

#endif // GF_ALL_H
