name: UbuntuBuild

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configurations:
        - { name: Linux,  shared: "ON",   mode: Debug     }
        - { name: Linux,  shared: "ON",   mode: Release   }
        - { name: Linux,  shared: "OFF",  mode: Debug     }

    name: Linux (${{ matrix.configurations.kind }} ${{ matrix.configurations.mode }})
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libboost-dev libfreetype6-dev zlib1g-dev libpugixml-dev libstb-dev

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: actions/checkout@v3
        with:
          repository: GamedevFramework/gf
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Configure gf
        run: cmake -DBUILD_SHARED_LIBS=${{ matrix.configurations.shared }} -DCMAKE_BUILD_TYPE=${{ matrix.configurations.mode }} -DGF_BUILD_GAMES=OFF -DGF_BUILD_EXAMPLES=OFF -DGF_BUILD_DOCUMENTATION=OFF -DCMAKE_UNITY_BUILD=ON -S ${{ github.workspace }} -B ${{ github.workspace }}/build

      - name: Build gf
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.configurations.mode }} --parallel

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.configurations.mode }} -T test --output-on-failure
